config/routes.rb
Rails.application.routes.draw do

  root to: "pages#splash"

  # resources :items, only: [:index, :show]
  get '/items', to: 'items#index'
  get '/items/:id', to: 'items#show', as: 'item'

  # resources :users, only: [:new, :create]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create', as: 'users'

  # resources :cart_items, only: [:edit]
  post '/cart_items', to: 'cart_items#create'
  delete '/cart_items/:id', to: 'cart_items#destroy'
  patch '/cart_items/:id', to: 'cart_items#update', as: 'cart_item'
  get '/cart_items/:id', to: 'cart_items#edit', as: 'edit_cart_item'

  # resources :orders, only: [:index, :create]
  get '/orders', to: 'orders#index', as: 'orders'
  post '/orders/', to: 'orders#create'

  # namespace admin, resources items, resources users, only show
  get    '/admin/items', to: 'admin/items#index', as: 'admin_items'
  post   '/admin/items', to: 'admin/items#create'
  get    '/admin/items/new', to: 'admin/items#new', as: 'new_admin_item'
  get    '/admin/items/:id/edit', to: 'admin/items#edit', as: 'edit_admin_item'
  get    '/admin/items/:id', to: 'admin/items#show', as: 'admin_item'
  patch  '/admin/items/:id', to: 'admin/items#update'
  delete '/admin/items/:id', to: 'admin/items#destroy'
  get    '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  get "/order", to: "orders#show"
  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/cart", to: "cart_items#index"
  get "/admin/dashboard", to: "admin/users#show"
  get "/:category", to: "categories#show"
  get "/*page", to: "errors#not_found"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items
  has_attached_file :avatar,
                    styles: {thumb: '100x100>',
                             square: '200x200#',
                             medium: '300x300>'},
                    default_url: "default.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true
  validates_numericality_of :price,  greater_than: 0


  def disabled_item?
    retired ? ["Item Retired", disabled: true] : ["Add to Cart", disabled: false]
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find_by(id: params[:id])
    redirect_to '/errors/not_found.html' unless @item
  end

  def new
    @categories = Category.all
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)

    if @item.save
      flash[:notice] = "Successfully created a new item"
      redirect_to admin_items_path
    else
      flash.now[:error] = @item.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      flash[:notice] = "Item has been updated"
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :category_id, :retired, :avatar)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:index]
  before_action :redirect_if_no_item, except: [:index]

  def index
    @items = Item.all
    @categories = Category.all
  end

  def show
  end

  private

  def set_item
    @item = Item.find_by(id: params[:id])
  end

  def redirect_if_no_item
    redirect_to "/errors/not_found.html" unless @item
  end
end

app/views/admin/items/edit.html.erb
<div class="container form-spacing">
  <div class="vertical-center-row">
    <div align="center">
      <h1>Edit Item</h1>

      <%= form_for @item, url:{:controller=>'admin/items', :action=>'update'} do |f| %>
        <p><%= f.text_field :name, placeholder: "Name" %></p>
        <p><%= f.text_field :description, placeholder: "Description" %></p>
        <p><%= f.number_field :price, step: "any", placeholder: "Price" %></p>
        <p><%= f.number_field :category_id, placeholder: "Category ID" %></p>
        <p ><%= f.label 'retired', "Retired" %>
        <%= f.radio_button :retired, true %></p>
        <p><%= f.label 'not_retired', "Not Retired" %>
        <%= f.radio_button :retired, false %></p>
        <p><%= f.submit  %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="cart">
  <div class="container">
    <div class="cart-top">
      <h1>All Items</h1>
    </div>
    <div class="cart-conclusion">

      <table>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Image</th>
          <th>Price</th>
          <th>Retired?</th>
          <th>Action</th>
        </tr>
        <% @items.each do |item| %>
          <tr class="item<%= item.id %>">
            <td><%= link_to item.name, item_path(item) %></td>
            <td><%= item.description %></td>
            <td><%= image_tag item.avatar.url(:square) %></td>
            <td><%= number_to_currency(item.price) %></td>
            <td><%= item.retired %></td>
            <td><%= link_to "Edit", edit_admin_item_path(item) %></td>
          </tr>
        <% end %>
        <tr>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container form-spacing">
  <div class="vertical-center-row">
    <div align="center">
      <h1>Item Creation Page</h1>
      <h3>Enter New Item Information:</h3>

      <%= form_for @item, url:{:controller=>'admin/items', :action=>'create'} do |f| %>
        <p><%= f.text_field :name, placeholder: "Name" %></p>
        <p><%= f.text_field :description, placeholder: "Description" %></p>
        <p><%= f.file_field :avatar %></p>
        <p><%= f.number_field :price, step: "any", placeholder: "Price" %></p>
        <p><%= f.number_field :category_id, placeholder: "Category ID" %></p>

        <p><%= f.submit class:"btn btn-primary" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<ul>
  <li><%= @item.name %></li>
  <ul>
    <li><%= @item.description %></li>
    <li><%= render partial: "shared/imagesmall", locals: { item:@item } %></li>
    <li><%= number_to_currency(@item.price) %></li>
    </li>
  </ul>
</ul>