config/routes.rb
Rails.application.routes.draw do

  root to: "pages#splash"

  # resources :items, only: [:index, :show]
  get '/items', to: 'items#index'
  get '/items/:id', to: 'items#show', as: 'item'

  # resources :users, only: [:new, :create]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create', as: 'users'

  # resources :cart_items, only: [:edit]
  post '/cart_items', to: 'cart_items#create'
  delete '/cart_items/:id', to: 'cart_items#destroy'
  patch '/cart_items/:id', to: 'cart_items#update', as: 'cart_item'
  get '/cart_items/:id', to: 'cart_items#edit', as: 'edit_cart_item'

  # resources :orders, only: [:index, :create]
  get '/orders', to: 'orders#index', as: 'orders'
  post '/orders/', to: 'orders#create'

  # namespace admin, resources items, resources users, only show
  get    '/admin/items', to: 'admin/items#index', as: 'admin_items'
  post   '/admin/items', to: 'admin/items#create'
  get    '/admin/items/new', to: 'admin/items#new', as: 'new_admin_item'
  get    '/admin/items/:id/edit', to: 'admin/items#edit', as: 'edit_admin_item'
  get    '/admin/items/:id', to: 'admin/items#show', as: 'admin_item'
  patch  '/admin/items/:id', to: 'admin/items#update'
  delete '/admin/items/:id', to: 'admin/items#destroy'
  get    '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  get "/order", to: "orders#show"
  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/cart", to: "cart_items#index"
  get "/admin/dashboard", to: "admin/users#show"
  get "/:category", to: "categories#show"
  get "/*page", to: "errors#not_found"
end

app/views/shared/_banner.html.erb
<!--banner-->

<div class="banner-bg banner-bg1">
	<%= render partial: "shared/topnav" %>
	<div class="caption">
		 <div class="slider">
					   <div class="callbacks_container">
						   <ul class="rslides" id="slider">
							    <li><h1>NACHOMOMS PALEO</h1></li>
						  </ul>
              <p class="med">More Paleo
        than all your most <em>hipster-paleo-diet-eating-crossfiting-friends</em>,<br>
        the <span><strong>ULTIMATE PALEO,</strong></span><br>the <span><strong>PALEOEST</strong></span></p>
              <%= link_to "SHOP", items_path, class:"morebtn" %>
					  </div>
				  </div>
	</div>
</div>
<!--/banner-->

app/views/shared/_cartbutton.html.erb
<% if item.retired? %>
  <%= button_to "Item Retired", cart_items_path(item_id: item.id), class:"btn_form", disabled: true %>
<% else %>
  <%= button_to "Add to Cart", cart_items_path(item_id: item.id), class:"btn_form" %>
<% end %>

app/views/shared/_categories.html.erb
<div id="cate" class="categories">
	 <div class="container">
		 <h3>CATEGORIES</h3>
		 <div class="categorie-grids">
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid1">
				 <h4>DINOSAUR MEAT</h4>
				 <p>It doesn't get anymore paleo than this!</p>
				 <a class="store" href="/meats">Shop</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid2">
				 <h4>DINOSAUR EGGS</h4>
				 <p>Fresh, Tender, &amp;  Innocent</p>
				 <a class="store" href="/eggs">Shop</a>
			 </div></a>
			 <a href="bicycles.html"><div class="col-md-4 cate-grid grid3">
				 <h4>PLANTS</h4>
				 <p>The original organic farm</p>
				 <a class="store" href="/plants">Shop</a>
			 </div></a>
			 <div class="clearfix"></div>
		 </div>
	 </div>
</div>

app/views/shared/_contact.html.erb
<div class="contact">
	<div class="container">
		<h3>CONTACT US</h3>
		<p>Please contact us for all inquiries and purchase options.</p>
		<form>
			 <input type="text" placeholder="NAME" required="">
			 <input type="text" placeholder="LAST NAME" required="">
			 <input class="user" type="text" placeholder="EMAIL@PLACE.COM" required=""><br>
			 <textarea placeholder="MESSAGE"></textarea>
			 <input type="submit" value="SEND">
		</form>
	</div>
</div>

app/views/shared/_head.html.erb
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %>
<link href="bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (Bootstrap's JavaScript plugins) -->
<script src="jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Nachomom, Paleo, Paleo Diet, Dinosaurs, Dinosaur Meat" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="jquery.easydropdown.js"></script>
<link href="nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="scripts.js" type="text/javascript"></script>
<!--js-->
<!---- start-smoth-scrolling---->
		<script type="text/javascript" src="move-top.js"></script>
		<script type="text/javascript" src="easing.js"></script>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
		</script>
<!---- start-smoth-scrolling---->

app/views/shared/_imagesquare.html.erb
<%= image_tag item.avatar.url(:square) %>

app/views/shared/_items.html.erb
<% all_items.each_slice(4).to_a.each do |items| %>
  <% items.each do |item| %>
    <%= link_to item_path(item) do %>
    <div class="bike">
      <%= render partial: "shared/imagesquare", locals: { item:item } %>
      <div class="bike-cost">
        <div class="bike-mdl">
          <h4>
            <%= item.name %>
            <span><%= number_to_currency(item.price) %></span>
          </h4>
        </div>
       <div class="bike-cart">
         <% if item.retired? %>
            <%= link_to "Item Retired", "", class:"buy" %>
          <% else %>
            <%= render partial: "shared/cartbutton", locals: {item:item} %>
          <% end %>

       </div>
       <div class="clearfix"></div>
      <% end %>

        </div>
      </div>
    <% end %>
  <% end %>
    <div class="clearfix"></div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NachomomsPaleo", root_path, class:"navbar-brand" %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><a href="#">Paleo Diet Resources</a></li>
        <!-- <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li> -->
        <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a> -->
        <!-- <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li> -->
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <a class="btn btn-default btn-lg" href="/cart" role="button">Cart
          <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a>


          <% if current_user %>
          <!-- <button type="button" class="btn btn-default btn-lg"> -->

          <!-- </button> -->
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>

          <!-- <li role="separator" class="divider"></li> -->
          <li><%= link_to "Login", login_path %> or <%= link_to "Create Account to Checkout", new_user_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>


    Cart: <%= @cart.count_all %> <%= link_to "View My Cart", cart_path %>

    <!-- <ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="#">Library</a></li>
    <li class="active">Data</li>
  </ol> -->
</div><!-- /.container-fluid -->
</nav>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_order.html.erb
<h4>Order Number:<%= order.id %></h4>
</div>
<div class="cart-conclusion">
<h5>Order Date: <%= Order.format_time(order.created_at) %></h5>
<h5>Order Status: <%= order.status %></h5>
<% if order.status == "cancelled" || order.status == "completed" %>
<%= Order.format_time(order.updated_at) %>
<% end %>
<table width="500px">
  <tr>
    <th>
      Name
    </th>
    <th>
      Quantity
    </th>
    <th>
      Price
    </th>
    <th>
      Subtotal
    </th>
  </tr>
  <% order_items.each do |order_item| %>
  <tr>
    <td>
      <%= link_to order_item.item.name, item_path(order_item.item) %>
    </td>
    <td>
      <%= order_item.quantity %>
    </td>
    <td>
      <%= number_to_currency(order_item.item.price) %>
    </td>
    <td>
      <%= number_to_currency(order_item.subtotal) %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td colspan="3">
      Grand Total:
    </td>
    <td>
      <%= number_to_currency(order.total_price) %>
    </td>

  </tr>

</table>

app/views/shared/_orders.html.erb
  <ul>
    <% orders.each do |order| %>
    <li>Order number : <%= order.id %> - <%= link_to "View Order Details", order_path(order_id: order.id) %></li>
    <% end %>
  </ul>

app/views/shared/_othernav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NachomomsPaleo", root_path, class:"navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if current_admin? %>
        <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>

        <% else %>
        <li><%= link_to "Shop", items_path %></li>
        <% end %>

      </ul>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li>

        <% if current_admin? %>
        <li><%= link_to "Items", admin_items_path %></li>

        <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>

        <% if current_user %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <li><%= link_to "Dashboad", dashboard_path %></li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
        <!-- <li role="separator" class="divider"></li> -->
        <li><%= link_to "Create Account to Checkout", new_user_path %></li>
        <% end %>

        <% end %>
      </li>
      <li><a class="btn btn-default btn-lg" href="/cart" role="button">Cart<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> <%= @cart.count_all %></a></li>

    </ul>
  </div>
</div>
</nav>

app/views/shared/_popular.html.erb
<div class="container">
	 <div class="bikes">
		 <h3>POPULAR ITEMS</h3>
     <div class="categorie-grids">
     <% sample.each do |item| %>
			 <div class="col-md-4">
				 <%= render partial: "shared/imagesmall", locals: { item:item } %>
				 <%= content_tag :h4, item.name %>
				 <%= content_tag :p, item.description %>
         <%= content_tag :p, number_to_currency(item.price) %><br />
				 <%= render partial: "shared/cartbutton", locals: {item:item} %>
			 </div>
       <% end %>
	 </div>
 </div>
</div>

app/views/shared/_shortbanner.html.erb
<!--banner-->

<div class="banner-bg banner-sec">
  <%= render partial: "shared/topnav" %>
</div>
<!--/banner-->

app/views/shared/_topnav.html.erb
<div class="container">
   <div class="header">
         <div class="logo">
         <a href="/"><%= image_tag "logo.png" %></a>
       </div>
      <div class="top-nav">
        <ul class="nav">
        <% if current_admin? %>
          <li><%= link_to "Admin Dashboard", admin_dashboard_path, class:"morebtn" %></li>
          <li><%= link_to "Items", admin_items_path, class:"morebtn" %></li>
          <li><%= button_to "Logout", logout_path, method: "delete", class:"morebtn" %></li>
        <% elsif current_user %>
          <li><%= link_to "Shop", items_path, class:"morebtn" %></li>
          <li><%= link_to "Dashboard", dashboard_path, class:"morebtn" %></li>
          <li><%= button_to "Logout", logout_path, method: "delete", class:"morebtn" %></li>
          <a class="shop" href="<%= cart_path %>"><%= image_tag "cart.png" %> &nbsp;<%= @cart.count_all %></a>
        <% else %>
          <li><%= link_to "Shop", items_path, class:"morebtn" %></li>
          <li><%= link_to "Create Account", new_user_path, class:"morebtn" %></li>
          <li><%= link_to "Login", login_path, class:"morebtn" %></li>
          <a class="shop" href="<%= cart_path %>"><%= image_tag "cart.png" %> &nbsp;<%= @cart.count_all %></a>
        <% end %>
    </ul>
     </div>
     <div class="clearfix"></div>
   </div>
</div>