config/routes.rb
Rails.application.routes.draw do

  root to: "pages#splash"

  # resources :items, only: [:index, :show]
  get '/items', to: 'items#index'
  get '/items/:id', to: 'items#show', as: 'item'

  # resources :users, only: [:new, :create]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create', as: 'users'

  # resources :cart_items, only: [:edit]
  post '/cart_items', to: 'cart_items#create'
  delete '/cart_items/:id', to: 'cart_items#destroy'
  patch '/cart_items/:id', to: 'cart_items#update', as: 'cart_item'
  get '/cart_items/:id', to: 'cart_items#edit', as: 'edit_cart_item'

  # resources :orders, only: [:index, :create]
  get '/orders', to: 'orders#index', as: 'orders'
  post '/orders/', to: 'orders#create'

  # namespace admin, resources items, resources users, only show
  get    '/admin/items', to: 'admin/items#index', as: 'admin_items'
  post   '/admin/items', to: 'admin/items#create'
  get    '/admin/items/new', to: 'admin/items#new', as: 'new_admin_item'
  get    '/admin/items/:id/edit', to: 'admin/items#edit', as: 'edit_admin_item'
  get    '/admin/items/:id', to: 'admin/items#show', as: 'admin_item'
  patch  '/admin/items/:id', to: 'admin/items#update'
  delete '/admin/items/:id', to: 'admin/items#destroy'
  get    '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  get "/order", to: "orders#show"
  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/cart", to: "cart_items#index"
  get "/admin/dashboard", to: "admin/users#show"
  get "/:category", to: "categories#show"
  get "/*page", to: "errors#not_found"
end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :item, :quantity

  def initialize(id, qty)
    @item = Item.find_by(id: id)
    @quantity = qty
    super(@item)
  end

  def subtotal
    item.price * quantity
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    set_redirect
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    flash[:notice] = "Successfully added to cart!"
    session[:cart] = @cart.contents
    redirect_to session[:redirect]
  end

  def index
    @items = @cart.mapped_values || {}
  end

  def update
    qty = params[:session][:quantity].to_i
    @cart.update(params[:item_id], qty)
    redirect_to cart_path
  end

  def destroy
    item = Item.find(params[:id])
    @cart.remove_item(params[:id])
    flash[:notice] = "Successfully removed <a href=\"/items/#{item.id}\">#{item.name}</a>!"
    redirect_to cart_path
  end
end

app/views/cart_items/index.html.erb
<div class="cart">
	<div class="container">
		<div class="cart-top">
			<%= link_to "<< home", root_path %>
		</div>

		<div class="col-md-9 cart-items">
			<h2>My Cart (<%= @cart.count_all %>)</h2>
			<% @items.each do |item| %>
			<div class="cart-header">
				<div class="cart-sec">
					<div class="cart-item cyc">
						<%= render partial: "shared/imagesquare", locals:{item:item} %>
					</div>
					<div class="cart-item-info">
						<h3><%= item.name %><span></span></h3>
						<div class="cart-remove"><%= button_to "X", cart_item_path(item), method: :delete %></div>
						<h4>Unit Price: <%= number_to_currency(item.price) %></h4>
						<h4>Subtotal: <%= number_to_currency(item.subtotal) %></h4>
						<%= form_for :session, url: cart_item_path(:id, {item_id: item.id}), html: {method: "patch"} do |f| %>
							<%= f.number_field :quantity, value: item.quantity, min: 1, class: "form-control input-small" %>
							<%= f.submit "Update Quantity", class:"cart-update" %>
						<% end %>
					</div>

					<div class="clearfix"></div>
				</div>
			</div>
			<% end %>
		</div>

		<div class="col-md-3 cart-total">
			<div class="price-details">
				<h3>Price Details</h3>
				<span>Total</span>
				<span class="total"><%= number_to_currency(@cart.total_price) %></span>
				<span>Discount</span>
				<span class="total">---</span>
				<span>Delivery Charges</span>
				<span class="total">Free Shipping! Today Only!</span>
				<div class="clearfix"></div>
			</div>
			<span class="total final"><h4 class="last-price">TOTAL
				<%= number_to_currency(@cart.total_price) %></h4></span>
				<div class="clearfix"></div>


				<% if current_user %>
				<% if @cart.contents.empty? %>
				<% else %>
				<%= button_to "Place Order", orders_path, class: "order" %>
				<% end %>
				<% else %>
				<%= button_to "Login to Checkout", login_path, method: :get, class:"order" %>
				<% end %>

			</div>
		</div>
	</div>