config/routes.rb
Rails.application.routes.draw do

  root to: "pages#splash"

  # resources :items, only: [:index, :show]
  get '/items', to: 'items#index'
  get '/items/:id', to: 'items#show', as: 'item'

  # resources :users, only: [:new, :create]
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create', as: 'users'

  # resources :cart_items, only: [:edit]
  post '/cart_items', to: 'cart_items#create'
  delete '/cart_items/:id', to: 'cart_items#destroy'
  patch '/cart_items/:id', to: 'cart_items#update', as: 'cart_item'
  get '/cart_items/:id', to: 'cart_items#edit', as: 'edit_cart_item'

  # resources :orders, only: [:index, :create]
  get '/orders', to: 'orders#index', as: 'orders'
  post '/orders/', to: 'orders#create'

  # namespace admin, resources items, resources users, only show
  get    '/admin/items', to: 'admin/items#index', as: 'admin_items'
  post   '/admin/items', to: 'admin/items#create'
  get    '/admin/items/new', to: 'admin/items#new', as: 'new_admin_item'
  get    '/admin/items/:id/edit', to: 'admin/items#edit', as: 'edit_admin_item'
  get    '/admin/items/:id', to: 'admin/items#show', as: 'admin_item'
  patch  '/admin/items/:id', to: 'admin/items#update'
  delete '/admin/items/:id', to: 'admin/items#destroy'
  get    '/admin/users/:id', to: 'admin/users#show', as: 'admin_user'
  get "/order", to: "orders#show"
  get "/dashboard", to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/cart", to: "cart_items#index"
  get "/admin/dashboard", to: "admin/users#show"
  get "/:category", to: "categories#show"
  get "/*page", to: "errors#not_found"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name,     presence: true
  validates :last_name,      presence: true
  validates :email,          presence: true, uniqueness: true
  validates :email,          format: { with: VALID_EMAIL_REGEX }
  validates :city,           presence: true
  validates :state,          presence: true
  validates :zipcode,        presence: true,
                             length: { minimum: 5 }

  enum role: ["default", "admin"]
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.first_name} #{@user.last_name}"
      redirect_to dashboard_path
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :password, :city, :state, :zipcode)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    set_redirect
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.first_name} #{@user.last_name}"
      redirect_to session[:redirect]
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(current_user.id)
    @orders = @user.orders
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :password, :city, :state, :zipcode)
  end
end

app/views/admin/users/show.html.erb
<div class="cart">
  <div class="container">
    <div class="cart-top">
      <h1>Welcome Administrator : <%= @user.first_name %></h1>
    </div>
    <div class="cart-conclusion">
      <table width="100%">
        <tr>
          <th>
          Admin Dashboard
          </th>
        </tr>
        <tr>
          <td>
            <%= link_to "Create New Items", new_admin_item_path %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to "View All Items", admin_items_path %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to "View All Orders - Coming Soon!", "#" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to "View All Users - Coming Soon!", "#" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to "Company News - Coming Soon!", "#" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to "Training - Coming Soon!", "#" %>
          </td>
        </tr>
        <tr>
        </tr>
      </table>
    </div>
  </div>
</div>